// Helpers that make content/ behave like an Obsidian vault.
import fs from 'node:fs';
import path from 'node:path';

const VAULT = path.resolve('content');
const ATTACH = path.join(VAULT, 'attachments');

// Pages generated by the site (not files in the vault) that [[wikilinks]] can point at.
const ROUTES = { publications: '/publications', notes: '/notes' };

/** All markdown files in the vault, relative to content/ (e.g. "notes/hello.md"). */
function markdownFiles() {
  return fs.readdirSync(VAULT, { recursive: true })
    .map(String)
    .filter((f) => /\.mdx?$/.test(f) && !f.startsWith('.'));
}

export function vaultFiles() {
  return [...markdownFiles(), ...Object.keys(ROUTES).map((r) => `${r}.md`)];
}

/** Where each markdown file ends up on the site. */
export function vaultPermalinks() {
  const out = Object.fromEntries(Object.entries(ROUTES).map(([r, url]) => [`${r}.md`, url]));
  for (const f of markdownFiles()) {
    const slug = f.replace(/\.mdx?$/, '').split(path.sep).slice(1).join('/');
    if (f.startsWith(`pages${path.sep}`)) out[f] = slug === 'home' ? '/' : `/${slug}`;
    else if (f.startsWith(`notes${path.sep}`)) out[f] = `/notes/${slug}`;
  }
  return out;
}

const slug = (s) => s.trim().toLowerCase().replace(/[^\p{L}\p{N}\s_-]/gu, '').replace(/\s/g, '-');

/** Fallback for links with no matching file: embeds → /attachments, otherwise a page slug. */
export function resolveUrl({ filePath, heading, isEmbed }) {
  if (isEmbed) return `/attachments/${filePath}`;
  const hash = heading ? `#${slug(heading)}` : '';
  return filePath ? `/${slug(filePath)}${hash}` : hash;
}

/** Obsidian writes [[page#Some Heading]]; rewrite those anchors to match the heading ids Astro generates. */
export function rehypeSlugWikiAnchors() {
  const walk = (node) => {
    const cls = node.properties?.className;
    const href = node.properties?.href;
    if (node.tagName === 'a' && typeof href === 'string' && String(cls).includes('internal') && href.includes('#')) {
      const [base, hash] = href.split('#');
      node.properties.href = `${base}#${slug(decodeURIComponent(hash))}`;
    }
    node.children?.forEach(walk);
  };
  return walk;
}

/** Serves content/attachments at /attachments in dev and copies it into the build. */
export function attachments() {
  return {
    name: 'vault-attachments',
    hooks: {
      'astro:server:setup': ({ server }) => {
        server.middlewares.use('/attachments', (req, res, next) => {
          const file = path.join(ATTACH, decodeURIComponent((req.url ?? '').split('?')[0]));
          if (!file.startsWith(ATTACH) || !fs.existsSync(file) || fs.statSync(file).isDirectory()) return next();
          fs.createReadStream(file).pipe(res);
        });
      },
      'astro:build:done': ({ dir }) => {
        if (fs.existsSync(ATTACH)) fs.cpSync(ATTACH, new URL('attachments', dir), { recursive: true });
      },
    },
  };
}
