"""Generate src/lib/land.ts: world land as an SVG path of 1° run-length rectangles
(equirectangular, x = lon + 180, y = 84 - lat). Source: Natural Earth 110m land (public domain).
Run once: python3 scripts/make-land.py
"""
import json, urllib.request

URL = 'https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_110m_land.geojson'
geo = json.load(urllib.request.urlopen(URL))

rings = []
for f in geo['features']:
    g = f['geometry']
    polys = g['coordinates'] if g['type'] == 'MultiPolygon' else [g['coordinates']]
    for poly in polys:
        rings.extend(poly)

def inside(lon, lat):
    hit = False
    for ring in rings:
        for (x1, y1), (x2, y2) in zip(ring, ring[1:]):
            if (y1 > lat) != (y2 > lat) and lon < x1 + (lat - y1) * (x2 - x1) / (y2 - y1):
                hit = not hit
    return hit

parts = []
for row in range(0, 140):          # lat 84 → -56
    lat = 84 - row - 0.5
    run = None
    for col in range(0, 361):
        land = col < 360 and inside(col - 180 + 0.5, lat)
        if land and run is None:
            run = col
        elif not land and run is not None:
            parts.append(f'M{run} {row}h{col - run}v1h-{col - run}z')
            run = None

with open('src/lib/land.ts', 'w') as out:
    out.write('// Generated by scripts/make-land.py from Natural Earth 110m land (public domain).\n')
    out.write('// viewBox 0 0 360 140: x = lon + 180, y = 84 - lat\n')
    out.write(f"export const LAND_PATH = '{''.join(parts)}';\n")
print(len(parts), 'runs')
